package stuba.bpbpdatabasemapper;
// Generated Apr 7, 2015 10:21:49 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * GtfsStopTimes generated by hbm2java
 */
public class GtfsStopTimes  implements java.io.Serializable {


     private Integer id;
     private GtfsStops gtfsStops;
     private GtfsTrips gtfsTrips;
     private Integer stopSequence;
     private Integer arrivalTime;
     private Integer departureTime;
     private Integer pickupType;
     private Integer dropOffType;
     private Set stopRealTimesHistories = new HashSet(0);

    public GtfsStopTimes() {
    }

    public GtfsStopTimes(GtfsStops gtfsStops, GtfsTrips gtfsTrips, Integer stopSequence, Integer arrivalTime, Integer departureTime, Integer pickupType, Integer dropOffType, Set stopRealTimesHistories) {
       this.gtfsStops = gtfsStops;
       this.gtfsTrips = gtfsTrips;
       this.stopSequence = stopSequence;
       this.arrivalTime = arrivalTime;
       this.departureTime = departureTime;
       this.pickupType = pickupType;
       this.dropOffType = dropOffType;
       this.stopRealTimesHistories = stopRealTimesHistories;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public GtfsStops getGtfsStops() {
        return this.gtfsStops;
    }
    
    public void setGtfsStops(GtfsStops gtfsStops) {
        this.gtfsStops = gtfsStops;
    }
    public GtfsTrips getGtfsTrips() {
        return this.gtfsTrips;
    }
    
    public void setGtfsTrips(GtfsTrips gtfsTrips) {
        this.gtfsTrips = gtfsTrips;
    }
    public Integer getStopSequence() {
        return this.stopSequence;
    }
    
    public void setStopSequence(Integer stopSequence) {
        this.stopSequence = stopSequence;
    }
    public Integer getArrivalTime() {
        return this.arrivalTime;
    }
    
    public void setArrivalTime(Integer arrivalTime) {
        this.arrivalTime = arrivalTime;
    }
    public Integer getDepartureTime() {
        return this.departureTime;
    }
    
    public void setDepartureTime(Integer departureTime) {
        this.departureTime = departureTime;
    }
    public Integer getPickupType() {
        return this.pickupType;
    }
    
    public void setPickupType(Integer pickupType) {
        this.pickupType = pickupType;
    }
    public Integer getDropOffType() {
        return this.dropOffType;
    }
    
    public void setDropOffType(Integer dropOffType) {
        this.dropOffType = dropOffType;
    }
    public Set getStopRealTimesHistories() {
        return this.stopRealTimesHistories;
    }
    
    public void setStopRealTimesHistories(Set stopRealTimesHistories) {
        this.stopRealTimesHistories = stopRealTimesHistories;
    }




}


