package stuba.bpbpdatabasemapper;
// Generated Apr 7, 2015 10:21:49 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * GtfsRoutes generated by hbm2java
 */
public class GtfsRoutes  implements java.io.Serializable {


     private GtfsRoutesId id;
     private GtfsAgencies gtfsAgencies;
     private String shortName;
     private Integer type;
     private String textColor;
     private Set poisInRouteses = new HashSet(0);
     private Set gtfsTripses = new HashSet(0);

    public GtfsRoutes() {
    }

	
    public GtfsRoutes(GtfsRoutesId id, GtfsAgencies gtfsAgencies) {
        this.id = id;
        this.gtfsAgencies = gtfsAgencies;
    }
    public GtfsRoutes(GtfsRoutesId id, GtfsAgencies gtfsAgencies, String shortName, Integer type, String textColor, Set poisInRouteses, Set gtfsTripses) {
       this.id = id;
       this.gtfsAgencies = gtfsAgencies;
       this.shortName = shortName;
       this.type = type;
       this.textColor = textColor;
       this.poisInRouteses = poisInRouteses;
       this.gtfsTripses = gtfsTripses;
    }
   
    public GtfsRoutesId getId() {
        return this.id;
    }
    
    public void setId(GtfsRoutesId id) {
        this.id = id;
    }
    public GtfsAgencies getGtfsAgencies() {
        return this.gtfsAgencies;
    }
    
    public void setGtfsAgencies(GtfsAgencies gtfsAgencies) {
        this.gtfsAgencies = gtfsAgencies;
    }
    public String getShortName() {
        return this.shortName;
    }
    
    public void setShortName(String shortName) {
        this.shortName = shortName;
    }
    public Integer getType() {
        return this.type;
    }
    
    public void setType(Integer type) {
        this.type = type;
    }
    public String getTextColor() {
        return this.textColor;
    }
    
    public void setTextColor(String textColor) {
        this.textColor = textColor;
    }
    public Set getPoisInRouteses() {
        return this.poisInRouteses;
    }
    
    public void setPoisInRouteses(Set poisInRouteses) {
        this.poisInRouteses = poisInRouteses;
    }
    public Set getGtfsTripses() {
        return this.gtfsTripses;
    }
    
    public void setGtfsTripses(Set gtfsTripses) {
        this.gtfsTripses = gtfsTripses;
    }




}


