package stuba.bpbpdatabasemapper;
// Generated Apr 7, 2015 10:21:49 PM by Hibernate Tools 3.6.0



/**
 * GtfsCalendarDates generated by hbm2java
 */
public class GtfsCalendarDates  implements java.io.Serializable {


     private Integer id;
     private String date;
     private Integer exceptionType;
     private String serviceIdAgencyId;
     private String serviceIdId;

    public GtfsCalendarDates() {
    }

    public GtfsCalendarDates(String date, Integer exceptionType, String serviceIdAgencyId, String serviceIdId) {
       this.date = date;
       this.exceptionType = exceptionType;
       this.serviceIdAgencyId = serviceIdAgencyId;
       this.serviceIdId = serviceIdId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }
    public Integer getExceptionType() {
        return this.exceptionType;
    }
    
    public void setExceptionType(Integer exceptionType) {
        this.exceptionType = exceptionType;
    }
    public String getServiceIdAgencyId() {
        return this.serviceIdAgencyId;
    }
    
    public void setServiceIdAgencyId(String serviceIdAgencyId) {
        this.serviceIdAgencyId = serviceIdAgencyId;
    }
    public String getServiceIdId() {
        return this.serviceIdId;
    }
    
    public void setServiceIdId(String serviceIdId) {
        this.serviceIdId = serviceIdId;
    }




}


