package stuba.bpbpdatabasemapper;
// Generated Apr 7, 2015 10:21:49 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * GtfsStops generated by hbm2java
 */
public class GtfsStops  implements java.io.Serializable {


     private GtfsStopsId id;
     private String name;
     private Double lat;
     private Double lon;
     private String zoneId;
     private Set stopRealTimesHistories = new HashSet(0);
     private Set gtfsStopTimeses = new HashSet(0);

    public GtfsStops() {
    }

	
    public GtfsStops(GtfsStopsId id) {
        this.id = id;
    }
    public GtfsStops(GtfsStopsId id, String name, Double lat, Double lon, String zoneId, Set stopRealTimesHistories, Set gtfsStopTimeses) {
       this.id = id;
       this.name = name;
       this.lat = lat;
       this.lon = lon;
       this.zoneId = zoneId;
       this.stopRealTimesHistories = stopRealTimesHistories;
       this.gtfsStopTimeses = gtfsStopTimeses;
    }
   
    public GtfsStopsId getId() {
        return this.id;
    }
    
    public void setId(GtfsStopsId id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Double getLat() {
        return this.lat;
    }
    
    public void setLat(Double lat) {
        this.lat = lat;
    }
    public Double getLon() {
        return this.lon;
    }
    
    public void setLon(Double lon) {
        this.lon = lon;
    }
    public String getZoneId() {
        return this.zoneId;
    }
    
    public void setZoneId(String zoneId) {
        this.zoneId = zoneId;
    }
    public Set getStopRealTimesHistories() {
        return this.stopRealTimesHistories;
    }
    
    public void setStopRealTimesHistories(Set stopRealTimesHistories) {
        this.stopRealTimesHistories = stopRealTimesHistories;
    }
    public Set getGtfsStopTimeses() {
        return this.gtfsStopTimeses;
    }
    
    public void setGtfsStopTimeses(Set gtfsStopTimeses) {
        this.gtfsStopTimeses = gtfsStopTimeses;
    }




}


