package stuba.bpbpdatabasemapper;
// Generated Apr 7, 2015 10:21:49 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * StopRealTimesHistory generated by hbm2java
 */
public class StopRealTimesHistory  implements java.io.Serializable {


     private Long id;
     private GtfsStops gtfsStops;
     private GtfsStopTimes gtfsStopTimes;
     private GtfsTrips gtfsTrips;
     private Integer realArrivalTime;
     private Integer realDepartureTime;
     private Date createdAt;

    public StopRealTimesHistory() {
    }
    
    public StopRealTimesHistory(GtfsStops gtfsStops, GtfsStopTimes gtfsStopTimes, GtfsTrips gtfsTrips, Integer realArrivalTime, Integer realDepartureTime) {
       this.gtfsStops = gtfsStops;
       this.gtfsStopTimes = gtfsStopTimes;
       this.gtfsTrips = gtfsTrips;
       this.realArrivalTime = realArrivalTime;
       this.realDepartureTime = realDepartureTime;
    }

    public StopRealTimesHistory(GtfsStops gtfsStops, GtfsStopTimes gtfsStopTimes, GtfsTrips gtfsTrips, Integer realArrivalTime, Integer realDepartureTime, Date createdAt) {
       this.gtfsStops = gtfsStops;
       this.gtfsStopTimes = gtfsStopTimes;
       this.gtfsTrips = gtfsTrips;
       this.realArrivalTime = realArrivalTime;
       this.realDepartureTime = realDepartureTime;
       this.createdAt = createdAt;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public GtfsStops getGtfsStops() {
        return this.gtfsStops;
    }
    
    public void setGtfsStops(GtfsStops gtfsStops) {
        this.gtfsStops = gtfsStops;
    }
    public GtfsStopTimes getGtfsStopTimes() {
        return this.gtfsStopTimes;
    }
    
    public void setGtfsStopTimes(GtfsStopTimes gtfsStopTimes) {
        this.gtfsStopTimes = gtfsStopTimes;
    }
    public GtfsTrips getGtfsTrips() {
        return this.gtfsTrips;
    }
    
    public void setGtfsTrips(GtfsTrips gtfsTrips) {
        this.gtfsTrips = gtfsTrips;
    }
    public Integer getRealArrivalTime() {
        return this.realArrivalTime;
    }
    
    public void setRealArrivalTime(Integer realArrivalTime) {
        this.realArrivalTime = realArrivalTime;
    }
    public Integer getRealDepartureTime() {
        return this.realDepartureTime;
    }
    
    public void setRealDepartureTime(Integer realDepartureTime) {
        this.realDepartureTime = realDepartureTime;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }




}


