package stuba.bpbpdatabasemapper;
// Generated Apr 7, 2015 10:21:49 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * TripPositions generated by hbm2java
 */
public class TripPositions  implements java.io.Serializable {


     private Long id;
     private GtfsTrips gtfsTrips;
     private double lat;
     private double lon;
     private double speed;
     private double accuracy;
     private int delay;
     private Date modifiedAt;
     private String state;

    public TripPositions() {
    }
    
    public TripPositions(GtfsTrips gtfsTrips, double lat, double lon, double speed, double accuracy, int delay, String state) {
       this.gtfsTrips = gtfsTrips;
       this.lat = lat;
       this.lon = lon;
       this.speed = speed;
       this.accuracy = accuracy;
       this.delay = delay;
       this.state = state;
    }

    public TripPositions(GtfsTrips gtfsTrips, double lat, double lon, double speed, double accuracy, int delay, Date modifiedAt, String state) {
       this.gtfsTrips = gtfsTrips;
       this.lat = lat;
       this.lon = lon;
       this.speed = speed;
       this.accuracy = accuracy;
       this.delay = delay;
       this.modifiedAt = modifiedAt;
       this.state = state;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public GtfsTrips getGtfsTrips() {
        return this.gtfsTrips;
    }
    
    public void setGtfsTrips(GtfsTrips gtfsTrips) {
        this.gtfsTrips = gtfsTrips;
    }
    public double getLat() {
        return this.lat;
    }
    
    public void setLat(double lat) {
        this.lat = lat;
    }
    public double getLon() {
        return this.lon;
    }
    
    public void setLon(double lon) {
        this.lon = lon;
    }
    public double getSpeed() {
        return this.speed;
    }
    
    public void setSpeed(double speed) {
        this.speed = speed;
    }
    public double getAccuracy() {
        return this.accuracy;
    }
    
    public void setAccuracy(double accuracy) {
        this.accuracy = accuracy;
    }
    public int getDelay() {
        return this.delay;
    }
    
    public void setDelay(int delay) {
        this.delay = delay;
    }
    public Date getModifiedAt() {
        return this.modifiedAt;
    }
    
    public void setModifiedAt(Date modifiedAt) {
        this.modifiedAt = modifiedAt;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }




}


